repos:
  - repo: https://github.com/mineiros-io/pre-commit-hooks
    rev: v0.3.1
    hooks:
      - id: phony-targets
      - id: shellcheck
      - id: markdown-link-check
        args: ['-p']   # When adding the -p flag, markdown-link-check will always with an exit code 0, even if dead links are found
        verbose: true  # Forces the output of the hook to be printed even when the hook passes.
