name: CI Pipeline

on: [push]

env:
  V: "1"
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SNYK_USERID: ${{ secrets.SNYK_USERID }}
  DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build & Push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker-image
        run: make docker/build
      - name: Try to execute tools
        run: make test/execute-tools
      - name: Run pre-commit hooks
        run: make test/pre-commit
      - name: Check for tool updates
        run: make check/updates
      - name: Test docker-image with snyk.io
        run: make test/snyk
      - name: Tag docker-image
        if: startsWith(github.ref, 'refs/tags/v')
        run: make docker/tag
      - name: Push docker-image to Docker Hub
        if: startsWith(github.ref, 'refs/tags/v')
        run: make docker/push
